### ISSUE TITLE
Scope v4.1.0 milestone

### ISSUE THREAD

**Issue by victoriadrake** [victoriadrake/hugo-theme-introduction#157]
This theme has seen a lot of active development, thanks 100% in part to its amazing community of users and @hanzei for championing it all!

Many things have changed in just the last few months and I think we're overdue for at least v4.1. I'd like some help deciding on its scope.

* __Comments?__ #119 could integrate Staticman for comments, if that's something this theme's users thinks is appropriate.
* __Usage?__ People seem to be using Introduction on many different platforms and services. Which ones would you like to see more closely supported?
* A note about supported Hugo versions will be included, per #147 

This is an open invitation for users of this theme to weigh in. What would you like to see added or changed?

**Comment by Sieboldianus** [comment]
It is perhaps not critical, but I love both the black and the white version. I thought about ways to deploy both on my website, e.g. have the white version deployed under www.*.com and the black version deployed under *.com (for this, I only need to compile the site twice with different `config.toml`'s passed with the `-t`-flag and rendered to different folders).

But ultimately, a button for switching between night/day would rock it all. This is what I've seen on many pages these days, but I am not sure if this can be accomplished with a static hugo page.

👍 regarding Staticman. Another option could be [commento](https://gitlab.com/commento/commento)

**Comment by VincentTam** [comment]
>  regarding (optional!) staticman. I don't like Disqus, since it blows up the page quite significantly in size, and it is also not open source, I'm against using such Software. Another option could be [commento](https://gitlab.com/commento/commento).

@Sieboldianus Thanks for positive feedback regarding to [Staticman](https://staticman.net).  You're right about Disqus.  Some of its drawbacks are discussed in

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
1. https://medium.com/remys-blog/ejecting-disqus-4120e9985823


To use Commento, there're [two options](https://docs.commento.io/installation/).  Since this theme is a minimal one, perhaps users might not mind [paying $5 per month](https://commento.io/pricing) to save the trouble of maintaining a self-hosted instance.

**Comment by VincentTam** [comment]
As promised in my previous comment, the Staticman integration UI has been improved (at least, for desktop display).

[![I + SM UI 19](https://framapiaf.s3.framasoft.org/framapiaf/media_attachments/files/004/298/254/original/9743843b174cf891.png)](https://vincenttam.frama.io/introduction/blog/hipster-ipsum/)

**Comment by hanzei** [comment]
TBH I would rather cut `v4.1.0` sooner then later. It's been a long time since `v4.0.0` and the release will also contain various bug fixes. Other features can just go into `v4.2.0`.

**Comment by VincentTam** [comment]
@hanzei Before cutting the line, can you please add in #158?  It aims at replacing all leading forward slashes so that the site can be correctly built in case of nonempty subpath in the `baseURL`.  Here's some related Hugo discussions:

1. "Make sure not to use a forward slash for URL": https://discourse.gohugo.io/t/hugo-themes-donts/17714/6?u=onedrawingperday
2. "Don’t use a leading forward slash if you’re going to format your URLs with `absURL` or `relURL`.": `https://discourse.gohugo.io/t/baseurl-with-path-lead-to-wrong-paths-generation/14992/2?u=vincenttam

**Comment by hanzei** [comment]
@VincentTam Given this is a bug fix: Surely. I will look into this in the next days.

**Comment by victoriadrake** [comment]
> Note that the merge conflicts are due to @victoriadrake's user name change.

Sorry ^^;

Since we've had no further feature requests, @hanzei I'm with you. Can we call it after the few remaining open bugs?
