### ISSUE TITLE
Custom CSS files

### ISSUE THREAD

**Issue by marceljay** [victoriadrake/hugo-theme-introduction#183]
Since I would like to avoid overriding your (nice and sophisticated) theme, I would work with the files in the main directory and keep the theme as a git submodule. 

Somehow, it though only looks up and processes files in /assets in the respective theme folders yet not in root directory.  This is also true for the custom .css files that can be added through the config.toml. 
In another theme I was trying, I could just add .sass files into assets and they were considering during by the compiler.

Thanks for clarification :)

**Comment by Athanasiamo** [comment]
I just added a custom css in the assets `assets/css/custom.css` in my root-dir and pointed the toml to that `css/custom.css` and that seemed to work fine for me.

**Comment by marceljay** [comment]
Not sure what was wrong, but now it works.

**Comment by jpkarlsberg** [comment]
Would anybody be willing to share a bit more detail on how to do this? I've created a css file at  `/assets/css/custom.css` and have added the following line to my `config.toml` file: `custom_css = ['assets/css/custom.css']`. I've also tried `customCSS` in place of `custom_css`, which is the language that appears in the instructions on custom CSS on the theme page. I'd be grateful for more specific instructions on adding a custom CSS file.

**Comment by jpkarlsberg** [comment]
Just posting an update in case others encounter a similar issue.

I should have copied the `config.toml` file from the `exampleSite` provided within the theme directory. Had I done so, I would have realized I was making the following mistakes
1. not including `[params]` before the custom CSS parameter.
2. not using the proper parameter for referencing custom CSS within the theme: `customCSS = ` rather than `custom_css = `
3. the path assumes that the custom CSS file is within the top level `assets` directory, so my path should have just reach `css/custom.css`.
