### ISSUE TITLE
Why not use CDN?

### ISSUE THREAD

**Issue by awhitford** [victoriadrake/hugo-theme-introduction#186]
I see there are some assets that are included in the template, such as JQuery, Owl Carousel, and Font Awesome.  Why not use a CDN instead of bundling the assets?

The [benefits](https://stackoverflow.com/questions/3832446/benefits-vs-pitfalls-of-hosting-jquery-locally) include:
1. Reduced latency because CDN files can be downloaded in parallel to files downloaded from your own website.
2. Reduced traffic on your site -- which is particularly valuable when you pay per GB of network bandwidth.

JQuery - see https://code.jquery.com/
Owl Carousel  - https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js
Font Awesome - see https://cdnjs.com/libraries/font-awesome

**Comment by hanzei** [comment]
To me it's mostly privacy. I don't want to make web developers use a CDN by default. Otherwise they are making all of there visitors request resources form a third party. 

Also 1. is not a valid argument. HTPP/2 even allows you to push assets to the clients before they are requesting it. Hence it can be faster if you are having the data on you own server.
