### ISSUE TITLE
Using HTML in the Markdown files

### ISSUE THREAD

**Issue by SachinPendse** [victoriadrake/hugo-theme-introduction#194]
Hi Victoria, 

Thank you so much for making this template --- it's beautiful and I am in the process of learning how to use it. I am trying to customize it a little and have run into some issues that I was hoping you might have some thoughts on.  

1. I have tried to use HTML (e.g. adding breaks with <br/>) in the individual markdown files, but whenever I type anything wrapped in an HTML tag, it disappears and it is unclear to me why. 

2. I want to create new pages that use the blog template but reduce the amount of white space in between different divs/reduce font size/change color --- I'm not sure how to go about doing that and would appreciate any guidance you have. 

3. I am not sure how to center things in the template (e.g. centering the "About me" page). Is there a way to do that using Markdown? Would love to hear your thoughts! 

Thank you again for all your help and for making this amazing template!

**Comment by victoriadrake** [comment]
Hello Sachin, and you're welcome!

1: Which version of Hugo are you running? (Find out with `hugo version`). If it's later than 0.60, you may need to add a [configuration parameter for Goldmark](https://gohugo.io/getting-started/configuration-markup#goldmark). See the setting for `unsafe`.

2 & 3: You can tinker with your site styles by editing the [Sass](https://sass-lang.com/) files - you'll need to learn a bit of syntax. Make sure you're running [extended Hugo](https://gohugo.io/getting-started/installing#fetch-from-github), so that the theme compiles them when you rebuild your site.

**Comment by SachinPendse** [comment]
Hi Victoria, 

Wow, thank you so much for the quick response. Yes, with regards to 1, that did the trick! And with regards to 2, thanks! I will use that to play around with the formatting. Thanks again! 

Best, 

Sachin

**Comment by victoriadrake** [comment]
You’re welcome Sachin!
