### ISSUE TITLE
No "all posts" button using Japanese

### ISSUE THREAD

**Issue by TsumaR** [victoriadrake/hugo-theme-introduction#199]
Hi Vicky，Thank you for making such a beautiful theme and I really like the theme you made.
There is a problem that bothers me, it is about the appearance of blog contents at home using Japanese.
Almost the whole text of one blog is displayed, and I don't see 'Read more' and 'All Posts'.
I would appreciate it if you could provide me with a solution.

![スクリーンショット 2020-03-30 3 57 04](https://user-images.githubusercontent.com/42291982/77857777-9fa0b300-723a-11ea-88b8-71fbec40657f.png)

**Comment by victoriadrake** [comment]
Hello,

I think the reason that the summary is so long is because [Hugo's automatic Summary function](https://gohugo.io/content-management/summaries/#automatic-summary-splitting) shows the first 70 words by default. If it is counting words by using whitespace, that will include quite a lot of text for the Japanese language.

To fix this, I would suggest trying to set `summaryLength` in your [site configuration](https://gohugo.io/getting-started/configuration/) to something shorter.

You can also [manually truncate your text](https://gohugo.io/content-management/summaries/#manual-summary-splitting) in the blog post.

I am not yet sure why "Read More" and "All Posts" does not show up, but I would start with trying the things above.

**Comment by TsumaR** [comment]
Dear Vicky,
Thank you for your kind and quick response.
I added `summaryLength` in my configuration and it works perfectly, thank you.
The reason for "Read More" and "All Posts" button did not show up was the lack of adding the `ja.toml` file to the i18n/ folder.
I apologize for the inconvenience caused by my lack of front engineering knowledge.
Best regards,

**Comment by victoriadrake** [comment]
I’m glad to know it worked! Please do ask if you need any other help.
