### ISSUE TITLE
About image frame reshaping

### ISSUE THREAD

**Issue by pandaero** [victoriadrake/hugo-theme-introduction#230]
I want to make the image that comes up in the about (in the example the image of a cup of coffee), to have rounded edges. I think I can accomplish this using a `border-radius` property for the image, but I am very new to this and don't know how to translate that into the front matter or wherever else it needs to go to be implemented. Any help?

Thanks,

**Comment by victoriadrake** [comment]
Thank you! That was helpful. My confusion was because this issue was opened in an unrelated repository. I'll transfer it to my Introduction Hugo theme repository, which is where I think you meant it to go.

To answer your question, yes, you can change the shape of the image border with the `border-radius` CSS property. The coffee cup picture in particular has the class name `avatar`, so you can set the property on this class to change just this image. To change all images, you'll want to set the property on `img`.

![Screenshot from 2020-08-03 19-15-54](https://user-images.githubusercontent.com/24644237/89236296-26391880-d5be-11ea-9361-0120273e4da7.png)

You can do this by placing your own CSS file under `assets/` then adding the file name to this line in the site `config`:

https://github.com/victoriadrake/hugo-theme-introduction/blob/master/exampleSite/config.toml#L15

**Comment by pandaero** [comment]
Oh, thank you! I guess I'll go back to scratching my head knowing it can be done within what's provided. :smiley:

**Comment by victoriadrake** [comment]
You're welcome! I personally find the MDN docs helpful, here's the one for `border-radius`: https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

Good luck on your coding journey!
