### ISSUE TITLE
Didn't manage to have images in blog posts

### ISSUE THREAD

**Issue by eauchat** [victoriadrake/hugo-theme-introduction#251]
I don"t know if this a mistake from mine, a bug, or a feature request, but here it is:

**Is your feature request related to a problem? Please describe.**
I was trying to put images in blog posts, but didn't manage.

I tried the two following ways:
*(in both examples, I have put an image named `image.jpg` in a `/content/blog/assets/` directory)*

### Using the metadata section in top of blog posts markdown files:
```md
---
title: "Post title"
date: 2020-09-29T06:00:00-02:00
image: "assets/image.jpg"
tags: ["some","tags"]
---

## Firstly
Hey hello.

## Secondly
Yo goodbye.
```

Doing this, nothing happen and the image is not shown.

### Using the markdown syntax in the blog post text:
```md
---
title: "Post title"
date: 2020-09-29T06:00:00-02:00
tags: ["some","tags"]
---

## Firstly
Hey hello.

## Secondly
Yo goodbye.

![img](assets/image.jpg)
```

Doing this, instead of seeing the image in the post, I see `![img](assets/image.jpg)` written.

**Describe the solution you'd like**
Ideally, both of those methods should work to add images in blog posts. But personally I have a preference for the second one, because it allows more flexibility in the positioning of the image, and to have multiple images.

**Comment by victoriadrake** [comment]
Hello!

I suspect that part of the issue is your image file path, which would be relative to your blog post and not the site root. For example, if your post is located at `https://example.com/blog/post-title/`, then the image file path as you've written it will be `https://example.com/blog/post-title/assets/image.jpg`. I suspect this is not what you meant to do.

If you instead add a `/` to the beginning of your image file path, it will be relative to your site root. In other words, writing `/assets/image.jpg` will make the image path: `https://example.com/assets/image.jpg`

The correct image path is determined by where the image is stored in your site directory in relation to the blog post in which you want the image to appear. If you can tell me the URL that your blog post appears at, I can help you determine the correct image path.

As an example, if your blog post is located at `content/blog/post-title.md` and your image is at `content/blog/assets/image.jpg`, then you would add your image in Markdown with:

```md
![image description](/blog/assets/image.jpg)
```

**Comment by eauchat** [comment]
Thank you @victoriadrake for the detailed explanation.
Indeed it was a problem of path to the image, I think it was due to a space in the image file name.
The file was in `blog/images/some file.png` and using `![description](/blog/images/some file.png)` wouldn't work.
I moved it to `blog/assets/some_file.png` and used `![description](/blog/assets/some_file.png)` and it worked fine.

Thanks again for the quality of the explanation, it helped me narrow down the possibilities and solve the issue :)
