### ISSUE TITLE
External Links for Social Icons / Footer?

### ISSUE THREAD

**Issue by winxthecat** [victoriadrake/hugo-theme-introduction#324]
**Is your feature request related to a problem? Please describe.**
Hi, I always prefer it, when a link to an external site opens in a new tab or new browser window. 

**Describe the solution you'd like**
I would love to have the Social icons on the home page (twitter, linkedin etc) and the footer links to be opened in a new window.

**Describe alternatives you've considered**
I tried all possible HTML options i could think of, such as 

    <a href="https::/test.TLD" target="_blank" rel="noopener"><span>TEXT</span> </a>
or 

    <a href="https::/test.TLD"  target="_blank> TEXT </a>

But it always gave me (when applied to the footer) such an error message: 
> Error: "(...)/config.toml:120:116": unmarshal failed: toml: expected newline but got U+0068 'h'

Do you have an idea how to do that? 

I love the theme, and this would be the cherry on top.

**Comment by victoriadrake** [comment]
The `config.toml` file thinks the first quote is the end of the value and expects a newline to follow it. That's why you're seeing that error -- quotes in the values here need to be escaped in order to render.

You can have a look at https://github.com/victoriadrake/hugo-theme-introduction/issues/321#issuecomment-1039010081 for my explanation of how to alter or override the theme's HTML files. You'll want to overwrite [the `social.html` partial](https://github.com/victoriadrake/hugo-theme-introduction/blob/master/layouts/partials/home/social.html) if you want to change this HTML entirely.

In https://github.com/victoriadrake/hugo-theme-introduction/commit/7584ca2c4f30db8fd9d1aa59b11f25efff0fbce8, Sascha added the ability to have arbitrary HTML attributes in the social links. This is probably the easiest way: add `target=\"_blank\" rel=\"noopener\"` for [the `html_attributes` line.](https://github.com/victoriadrake/hugo-theme-introduction/commit/7584ca2c4f30db8fd9d1aa59b11f25efff0fbce8#diff-a22ce72f559279e2b268c61544e9e67d3bec733d98c878c79ea381623539069cR60)
